### ISSUE TITLE
Restarting workspace after feature installation does not take into account changes to eclipse.ini

### ISSUE THREAD

**Issue by robstryker** [eclipse-equinox/p2#166] opened 2022-11-03 16:49 UTC
Take a feature installation that has a p2.inf file as follows:

```
instructions.configure=\
org.eclipse.equinox.p2.touchpoint.eclipse.addJvmArg(jvmArg:--add-opens=java.base/java.security=ALL-UNNAMED);

instructions.unconfigure=\
org.eclipse.equinox.p2.touchpoint.eclipse.removeJvmArg(jvmArg:--add-opens=java.base/java.security=ALL-UNNAMED);
```

When this feature is installed via the UI, eclipse will come up with a dialog asking you to restart the IDE to apply the software update. When you select "Restart Now", the workspace will restart. The expected changes listed above will be physically added to the installation's eclipse.ini file. But when the workspace starts, these specific add-opens will not be active. 

If you then go restart the workbench one more time, the changes are applied to the running VM as expected. 

This would indicate a bug in the p2's software update - restart action where it fails to properly recognize or apply changes to eclipse.ini.

**Comment by mickaelistria** [comment] 2022-11-03 17:30
Was also reported as https://bugs.eclipse.org/bugs/show_bug.cgi?id=551378

**Comment by jonahgraham** [comment] 2023-08-28 23:22
IIUC there is already some [special handling to support changing the JVM](https://github.com/eclipse-equinox/p2/blob/c738408a533dd264182ecfffcd8c2dfdad62d337/bundles/org.eclipse.equinox.p2.touchpoint.eclipse/src/org/eclipse/equinox/internal/p2/touchpoint/eclipse/actions/SetJvmAction.java#L72-L103) and this change is to ensure other settings are done too. 

As an implementation idea it may be best to fully restart the eclipse process rather than reusing the existing eclipse process with special handling for what changed. That would mean that all the eclipse.ini settings would be recalculated the same as a fresh launch, and items such as the correct splash screen will be displayed on restart (in cases of updating versions of Eclipse IDE).

**Comment by jonahgraham** [comment] 2023-08-28 23:23
Note that [Eclipse IDE WG Funded Development Effort #24](https://gitlab.eclipse.org/eclipse-wg/ide-wg/ide-wg-dev-funded-efforts/ide-wg-dev-funded-program-planning-council-top-issues/-/issues/24) has been raised to resolve this problem.

**Comment by stephan-herrmann** [comment] 2023-08-30 17:07
See also 
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=323565
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=531112

**Comment by jonahgraham** [comment] 2023-09-05 16:46
There is a lot of history here - thanks @stephan-herrmann for providing more of it.

One main thing that is unclear to me is why restart can't/doesn't do a full cold restart. Maybe no one interested in this in the past had the knowledge necessary to change the launcher, or perhaps a new "restart" mechanism (return code) needs to be added to do a cold-restart.

Answering the above will be part of what is needed to successfully resolve this issue.

**Comment by laeubi** [comment] 2023-09-06 03:31
@jonahgraham not sure if it is relevant today but some things to consider regarding "cold" restart:

1. You can launch Equinox (!) applications without a launcher and therefore it should work at least without a native launcher as well, this is especially important if you run the application from within Eclipse
2. Killing the JVM process can have slightly higher times unless the application is up again
3. In general a JVM can host many different code (e.g. you can embed Equinox in a webcontainer) or even run multiple frameworks in parallel, having one of the "kill" the JVM might not be what one desire

Of course for a single deployed instance (e.g. Eclipse IDE) some or even all of the mentioned things are irrelevant, but the launcher code itself is generic code.

**Comment by jonahgraham** [comment] 2023-09-06 14:12
Thanks @laeubi for the extra context - someone taking on [the dev effort](https://gitlab.eclipse.org/eclipse-wg/ide-wg/ide-wg-dev-funded-efforts/ide-wg-dev-funded-program-planning-council-top-issues/-/issues/24) should be taking that into consideration to makes sure non Eclipse IDE style workflows continue to work as expected.

**Comment by merks** [comment] 2023-09-20 15:38
@mickaelistria 

That's a very constructive suggestion.  It is easy to implement compared to trying to relaunch the application completely from scratch on three differ platforms...

**Comment by laeubi** [comment] 2023-09-21 04:29
The message is way to complicated for a user to understand, I would make it less "technical" and simply mention that some changes require a *shutdown* of the application to take effect with the choice to "Only Restart now", "Shutdown Application now", "Do nothing and proceed" or similar.

**Comment by jonahgraham** [comment] 2023-09-28 13:32
The [Eclipse IDE WG Funded Development Effort #24](https://gitlab.eclipse.org/eclipse-wg/ide-wg/ide-wg-dev-funded-efforts/ide-wg-dev-funded-program-planning-council-top-issues/-/issues/24) is to implement the complete solution - i.e. not just blocking restart if eclipse.ini is modified. If there ends up being reasons or time delays that prevent getting the full solution implemented and integrated then starting with not allowing restart as discussed in the last few comments makes sense.

**Comment by merks** [comment] 2023-09-28 14:08
During various discussed I also saw comments about editing the *.ini manually and then restarting.  Probably that doesn't work either, does it?  It would certainly be very nice (and expected) that a restart properly re-reads everything including the eclipse.ini and the config.ini, regardless of whether it was p2 that made changes or the user.  

I'm just noting this because I'm not sure that the restart problem is actually a p2 problem rather than purely an equinox launcher problem.

**Comment by laeubi** [comment] 2023-09-28 14:11
> During various discussed I also saw comments about editing the *.ini manually and then restarting. Probably that doesn't work either, does it?

If you mean `File > Restart` then probably no, but honestly I never use this functionality but always close the program, make modifications and start it then again ...

**Comment by umairsair** [comment] 2023-11-17 16:48
All, kindly check the linked PRs.

**Closed** 2024-01-29 12:06 UTC

**Comment by merks** [comment] 2024-02-03 10:32
@umairsair 

I'm not sure if it's related, but I suspect so.  It can no longer restart a debug launched RCP/IDE application.  Trying to restart just terminates the application rather than starting a newly-launched debug session.

On the plus side, when testing updating a 2023-12 installation to 2023-04, the splash screen on restart displayed the updated splash screen, so that really great!!  🏆

**Comment by umairsair** [comment] 2024-02-04 02:10
@merks can you please share the exact eclipse command that you are invoking?

**Comment by merks** [comment] 2024-02-04 07:44
I'm on Windows.  I think it's reproducible with any launch:

![image](https://github.com/eclipse-equinox/p2/assets/208716/eb62317a-0022-4559-a6ea-5d0a98f49d22)

E.g., from this from setup:

https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#creating-an-eclipse-development-environment

It launches a process like this:

> "C:\Program Files\Java\jdk-17.0.9+9\bin\javaw.exe" -XX:+ShowCodeDetailsInExceptionMessages -agentlib:jdwp=transport=dt_socket,suspend=y,address=localhost:63244 -Xms256m -Xmx2048m -Duser.home=D:\Users\merks -Declipse.pde.launch=true --add-modules=ALL-SYSTEM -Djava.security.manager=allow -Dfile.encoding=UTF-8 -Dstdout.encoding=UTF-8 -Dstderr.encoding=UTF-8 -classpath D:\Users\merks\platform-sdk-4.30\git\equinox\bundles\org.eclipse.equinox.launcher\bin; org.eclipse.equinox.launcher.Main -launcher D:\Users\merks\platform-sdk-4.30\ws\.metadata\.plugins\org.eclipse.pde.core\.install_folders\1706880906456\eclipse.exe -name Eclipse -showsplash 600 -product org.eclipse.sdk.ide -data D:\Users\merks\platform-sdk-4.30\ws/../runtime-workspace -configuration "file:D:/Users/merks/platform-sdk-4.30/ws/.metadata/.plugins/org.eclipse.pde.core/Runtime Workspace/" -dev "file:D:/Users/merks/platform-sdk-4.30/ws/.metadata/.plugins/org.eclipse.pde.core/Runtime Workspace/dev.properties" -os win32 -ws win32 -arch x86_64 -nl en_US -consoleLog

But I debugged further and it's clear that it's intended that the process exits with exit code 24 whereas formerly it was exit code 23.  I.e., I debugged an older Eclipse version and saw that here too the process terminates completely but with a different exit code and of course the java process is launched directly, so no native launcher is involved.  So I suspect that it is the debug framework that needs to consider the new exit code value.  

I'll have a look where that code might be.  At this point I think there is nothing wrong with your changes but rather downstream needs to be adapted.  And, as I said, the new behavior seeing the updated splash screen after an update is really great!

**Comment by merks** [comment] 2024-02-04 07:53
FYI, I am looking at these as potentially needing further attention:

![image](https://github.com/eclipse-equinox/p2/assets/208716/c1095e2b-db63-4d23-a49a-8078225b5693)

Only the one is in the launcher and maybe that should consider value 24 as well, but when I debug the exit logic it does end up setting 24 as the exit code, which looks correct and intended:

![image](https://github.com/eclipse-equinox/p2/assets/208716/7394d25e-6b8f-40f1-91d9-182ed57e153b)

**Comment by umairsair** [comment] 2024-02-04 10:35
@merks ,

I have reproduced the issue.

I'll debug on my end. It should not ever exit with exit code 24 in PDE workflow.

**Comment by merks** [comment] 2024-02-04 12:12
We might be good to revert the other changes if that's the case...

**Comment by umairsair** [comment] 2024-02-04 12:50
@merks ,

Kindly check following PR and see if it handles all the concerns?

https://github.com/eclipse-platform/eclipse.platform.ui/pull/1622
