### ISSUE TITLE
[p2.director] Missing constraints on org.sat4j.core

### ISSUE THREAD

**Issue by Phillipus** [eclipse-equinox/p2#35] opened 2022-04-15 16:05 UTC
I'm testing our RCP app against the latest 4.24 I builds. This is the `.target` file:

```
<target name="Archi Dev">
<locations>
    <location includeAllPlatforms="true" includeConfigurePhase="true" includeMode="slicer" includeSource="true" type="InstallableUnit">
        <repository location="https://download.eclipse.org/eclipse/updates/4.24-I-builds/I20220414-1800/"/>
        <unit id="org.eclipse.ecf.filetransfer.httpclient5.feature.feature.group" version="0.0.0"/>
        <unit id="org.eclipse.ecf.core.feature.feature.group" version="0.0.0"/>
        <unit id="org.eclipse.ecf.core.ssl.feature.feature.group" version="0.0.0"/>
        <unit id="org.eclipse.ecf.filetransfer.feature.feature.group" version="0.0.0"/>
        <unit id="org.eclipse.ecf.filetransfer.ssl.feature.feature.group" version="0.0.0"/>
        <unit id="org.eclipse.emf.common.feature.group" version="0.0.0"/>
        <unit id="org.eclipse.emf.ecore.feature.group" version="0.0.0"/>
        <unit id="org.eclipse.equinox.core.feature.feature.group" version="0.0.0"/>
        <unit id="org.eclipse.equinox.p2.core.feature.feature.group" version="0.0.0"/>
        <unit id="org.eclipse.equinox.p2.extras.feature.feature.group" version="0.0.0"/>
        <unit id="org.eclipse.equinox.sdk.feature.group" version="0.0.0"/>
        <unit id="org.eclipse.sdk.ide" version="0.0.0"/>
    </location>
</locations>
</target>
```

When I set this as the target in Eclipse and then try to debug the RCP app by launching it from its `.product` file I get the following error:

![validation](https://user-images.githubusercontent.com/600504/163593539-76d31585-d036-4e8c-933f-fe53ddd4fba2.png)

**Comment by merks** [comment] 2022-04-15 16:48
@mickaelistria might this be a side effect of not including these in the feature?

https://github.com/mickaelistria/p2/commit/b73f4ddf0b6131e15e41807581225a6db8cbaa53

I think the launcher when based on features will overlook plugins dependencies.

**Comment by Phillipus** [comment] 2022-04-15 17:00
`I20220411-1800` is OK, but not `I20220412-1800`

**Comment by merks** [comment] 2022-04-15 18:09
What happens if you change to planner instead of slicer?

I think PDE changed stuff related to product launches too...

**Comment by Phillipus** [comment] 2022-04-15 18:12
> What happens if you change to planner instead of slicer?

Same problem.

**Comment by merks** [comment] 2022-04-15 18:48
Are the missing plugins in the target platform?  If so then it’s more an issue in the launch configuration.

**Comment by Phillipus** [comment] 2022-04-15 19:14
> I think PDE changed stuff related to product launches too...

I think there's something in this.

I'm using Eclipse 4.23 with the target set to 4.24 I build. When I click "Launch an Eclipse application in Debug mode" on the `.product` editor it creates a Launch Configuration. That Launch Configuration is automatically set to "Launch with: Plug-ins selected below" and the `org.sat4j.*` plug-ins are not selected.

Now I just downloaded the latest Eclipse 42.4 I build and tried the same thing, This time the Launch Configuration is created and automatically set to "Launch with: Features selected below" and there is no error.

(If I manually change the  Launch Configuration to "Launch with: Plug-ins selected below" then the `org.sat4j.*` plug-ins are not selected, as before.)

So, knowing this, I went back to my Eclipse 4.23 install and manually switched the Launch Configuration to "Launch with: Features selected below" and again there is no error.

So, I guess things have changed in PDE?

**Comment by merks** [comment] 2022-04-16 05:35
If it all works correctly in 4.24 then there isn't much that needs to be done, right?  After all sat4j isn't missing, it's just not in the launch configuration.  But it does sound like removing sat4j from the feature changed the behavior for 4.23.  But then, why is the resources plugin also missing?  That seems completely unrelated to p2.

**Comment by Phillipus** [comment] 2022-04-16 07:47
> But then, why is the resources plugin also missing?

I build `I20220412-1800` has only the two `sat4j` plug-ins not being added to the launch configuration which matches the date when they were removed from the feature. The `org.eclipse.core.resources` plug-in goes missing in `I20220414-1800` (or perhaps the day before that, I need to check) so perhaps a similar thing happened elsewhere?

**Comment by merks** [comment] 2022-04-16 07:50
@mickaelistria @laeubi 

Guys, I get the sense that removing inclusions of sat4j from the feature was not a good idea and that this has unexpected consequences that we'd be better off avoiding...

**Comment by laeubi** [comment] 2022-04-16 08:07
> I think the launcher when based on features will overlook plugins dependencies.

Nope this is 'intentional' (from PDE) @HannesWell added a new option to include additional requirements when launching products.

**Comment by HannesWell** [comment] 2022-04-16 17:15
> 
> Now I just downloaded the latest Eclipse 42.4 I build and tried the same thing, This time the Launch Configuration is created and automatically set to "Launch with: Features selected below" and there is no error.
>
> So, I guess things have changed in PDE?


That's right. Your analysis reflects pretty well what I recently have changed in PDE.

With [Bug 544838](https://bugs.eclipse.org/bugs/show_bug.cgi?id=544838) for a Feature-based product a Feature-based launch is created when you launch a feature-based product.

Feature based launches automatically add requirements (required-bundles, imported-packages, but also feature requirements as well as requirements defined by the application) if they are not contained in the closure of (transitively) included plug-ins and features of the features specified in the product/launch-configuration.
Some parts of this are already done for a while, some has already been improved for the latest 2022-03 release:
https://www.eclipse.org/eclipse/news/4.23/pde.php#eclipse-applications-launching

With [Bug 544838](https://bugs.eclipse.org/bugs/show_bug.cgi?id=544838) this behavior became configurable for launch-configurations and was also implemented for plugin-based launches.
From now on you can choose for a launch-config if only the specified plug-ins (for a plug-in based launch) respectively features and their contained features/plugin (for a feature based launch) should be included into the launched application or if all requirements should automatically be included as well.
In both cases the default reflects the previous behavior: For feature-based launches requirements are included for plug-in based launches not. So in the latter case, by default the launched application only consists of the specified plug-ins.
Once I have completed the implementation for [Bug 570760](https://bugs.eclipse.org/bugs/show_bug.cgi?id=570760) you can even enable/disable the inclusion of requirements on product level (first only for launches from the IDE, but I expect Tycho/P2 to follow).

Please note that the requirements are not added to the list of features/plug-ins in the launch-config! If the option to include requirements is enabled, the requirements are computed during each launch and are just added to the set of launched bundles during launch. For plug-in based launches this does not happen by default, which is the explanation for the behavior you have observed. Nevertheless sat4j will not be listed in the launch config in any case, because it is not necessary anymore. But if you wish you can still add it.

All these changes simplify setting up Eclipse products. For example you can now build with Tycho or launch from the IDE the Eclipse-SDK by defining a product that only contains the `org.eclipse.sdk` feature.
Please also note [578644](https://bugs.eclipse.org/bugs/show_bug.cgi?id=578644), but it should not have a negative impact if you build your product with Tycho and use that as well. The main goal of all the mentioned changes was to have the same bundles (as far as possible) in a Eclipse product regardless if it was build with Tycho and the executable is launched or if you launch the product from the Eclipse IDE (driven by PDE).

So if you are using Eclipse 2022-06 M1 (which is available since yesterday) your problem should be solved.

**Comment by Phillipus** [comment] 2022-04-16 18:20
@HannesWell Thanks for the comprehensive explanation!

> or launch from the IDE the Eclipse-SDK by defining a product that only contains the org.eclipse.sdk feature.

That will be handy. :-)

> Please also note [578644](https://bugs.eclipse.org/bugs/show_bug.cgi?id=578644), but it should not have a negative impact

I use Fragments for Unit tests and I notice these don't get added to the launch config, which is nice.

> So if you are using Eclipse 2022-06 M1 (which is available since yesterday) your problem should be solved.

Indeed. But getting back to the original issue report here, there will be users on older versions of Eclipse targetting 4.24 and later. And maybe also if a launch config is based on plug-ins there will be some plug-ins not added to the launch config. That's not for me to argue for or against, though, I leave that up to the devs here. :-)

**Comment by HannesWell** [comment] 2022-04-16 20:05
> @HannesWell Thanks for the comprehensive explanation!

You are very welcome and I'm glad the change is appreciated. :)

I have to add that I will add a corresponding new and noteworthy entry for the next release (I just did not have the time for it).


> > So if you are using Eclipse 2022-06 M1 (which is available since yesterday) your problem should be solved.
> 
> Indeed. But getting back to the original issue report here, there will be users on older versions of Eclipse targetting 4.24 and later. And maybe also if a launch config is based on plug-ins there will be some plug-ins not added to the launch config. That's not for me to argue for or against, though, I leave that up to the devs here. :-)

If you use a launch-config (and with Eclipse 2022-06 also a product) that is based on plug-ins features are not considered while launching, so a user has to specify sat4j (in this case) anyway.

What could indeed be considered problematic in the first place is when using the new version of p2 with an older Eclipse version. But IIRC PDE shows a warning to the user in case the target-platform targets a newer version than the running Eclipse-IDE and recommends to update the IDE.
So since this case is discouraged anyway and the only way to support that would be to revert PR #31, I tend to say we don't have to support it.

**Comment by akurtakov** [comment] 2022-04-20 08:14
As per other comments for developing against latest Eclipse it's highly recommended to use latest M-build (if developing Eclipse SDK itself even I-build). The issue is not there when using latest development builds (thanks @HannesWell !) and could be workarounded for people having to use some fixed old version and have quite positive effect on releng. Verification builds broken due to feature having to be touched in another git repository is not fun job and totally confuses people as it's unrelated to their work. Not to mention not being able to really verify dependency update automatically as features in various repos have to be touched.
With all of the above said I'm closing this issue as third party dependencies will be included less and less in features and let p2 do its work based on dependency information in project bundles.

**Closed by akurtakov** 2022-04-20 08:14 UTC

**Comment by Phillipus** [comment] 2022-05-18 09:49
Testing now with I20220428-1800 as dev environment and a target of I20220517-1800 with the target file:


```xml
<target name="Archi">
<locations>
    <location includeAllPlatforms="true" includeConfigurePhase="true" includeMode="slicer" includeSource="true" type="InstallableUnit">
        <repository location="https://download.eclipse.org/eclipse/updates/4.24-I-builds/"/>
        <unit id="org.eclipse.ecf.filetransfer.httpclient5.feature.feature.group" version="1.1.600.v20220215-0126"/>
        <unit id="org.eclipse.ecf.core.feature.feature.group" version="1.6.1.v20211005-1944"/>
        <unit id="org.eclipse.ecf.core.ssl.feature.feature.group" version="1.1.501.v20210409-2301"/>
        <unit id="org.eclipse.ecf.filetransfer.feature.feature.group" version="3.14.1800.v20220215-0126"/>
        <unit id="org.eclipse.ecf.filetransfer.ssl.feature.feature.group" version="1.1.401.v20210409-2301"/>
        <unit id="org.eclipse.emf.common.feature.group" version="2.26.0.v20220325-0806"/>
        <unit id="org.eclipse.emf.ecore.feature.group" version="2.28.0.v20220426-0617"/>
        <unit id="org.eclipse.equinox.core.feature.feature.group" version="1.13.600.v20220516-2155"/>
        <unit id="org.eclipse.equinox.p2.core.feature.feature.group" version="1.6.1400.v20220512-1321"/>
        <unit id="org.eclipse.equinox.p2.extras.feature.feature.group" version="1.4.1600.v20220512-1321"/>
        <unit id="org.eclipse.equinox.sdk.feature.group" version="3.23.400.v20220516-2155"/>
        <unit id="org.eclipse.sdk.ide" version="4.24.0.I20220517-1800"/>
    </location>
</locations>
</target>
```

Again, I am getting missing sat4j:

![sat4j](https://user-images.githubusercontent.com/600504/169010679-7a918179-9d9e-4363-9390-197be359fe25.png)

This time the sat4j files are not even present in the list of plugins in the Content section of the target file.

**Comment by Phillipus** [comment] 2022-05-18 10:06
The sat4j files go missing from target version `I20220510-1800`

Target content of `I20220509-1800`:

![I20220509-1800](https://user-images.githubusercontent.com/600504/169014309-bef202a7-d981-40a8-bbc0-9f4ffea9ef24.png)

Target content of `I20220510-1800`:

![I20220510-1800](https://user-images.githubusercontent.com/600504/169014333-9b7d7f33-e116-4f1a-93b6-2137e498139e.png)

Is this a bug or am I doing something wrong?

**Comment by mickaelistria** [comment] 2022-05-18 10:09
Make your target platform use "planner" mode instead of "slicer" if you want it to properly resolve dependencies.

**Comment by merks** [comment] 2022-05-18 10:13
This is a side effect of this change:

https://github.com/eclipse-equinox/p2/issues/28

**Comment by Phillipus** [comment] 2022-05-18 10:19
> Make your target platform use "planner" mode instead of "slicer" if you want it to properly resolve dependencies.

That worked, thank-you.

What is the difference between planner and slicer? I've been, perhaps mistakenly using "slicer" for a long time now. Are there any side-effects of using "planner". I'm targetting for a multi-platform RCP app.

> This is a side effect of this change:

Thanks for the heads-up, Ed.

**Comment by Phillipus** [comment] 2022-05-18 10:59
Using "planner" instead of "slicer" creates a problem for me because "slicer" will include multi-platform plug-ins in the target, whereas "planner" only includes the plug-ins for the host OS.

I have a Feature Project that is multi-platform and contains these plug-ins:

`org.eclipse.equinox.security.macosx`
`org.eclipse.equinox.security.win32.x86_64`

When I work on Windows machine the `org.eclipse.equinox.security.macosx` cannot be found.

**Comment by laeubi** [comment] 2022-05-18 11:20
Planner mode is slower and has some restrictions (as you already noticed), the usual way to "solve" the problem is to have one feature for each platform and include this in a "bigger one" with optional=true

**Comment by merks** [comment] 2022-05-18 11:28
@laeubi 

I don't think your comment is accurate.  It is not usual to have one feature per platform, it's usual to include fragments for each different platform in a single feature:

![image](https://user-images.githubusercontent.com/208716/169027829-43c926f0-22dd-42c1-a8dc-c9dddb998307.png)

Here too we see warnings because we didn't resolve all platforms in the TP.

Planner is a mode that works like when you create an installation, i.e., for a single platform, and ensure that all requirements are satisfied. Slicer follows all the transitive includes (so does not follow bundles requiring other bundles or other packages).  It doesn't matter what's slower or faster, it matters what ends up in the target platform...

@Phillipus 

Perhaps the only option is to explicitly include in your target platform the bundles that were removed from the p2 core feature.

**Comment by Phillipus** [comment] 2022-05-18 11:37
> Perhaps the only option is to explicitly include in your target platform the bundles that were removed from the p2 core feature (and continue to use slicer mode).

Thanks, Ed. I'm trying this option. But I don't know where the `sat4j` plug-ins are now located to add to my target file.

**Comment by laeubi** [comment] 2022-05-18 11:43
> I don't think your comment is accurate. It is not usual to have one feature per platform, it's usual to include fragments for each different platform in a single feature:

I can only tell that this works with planner mode (!) if you use the feature with slicer it does not matter and PDE don't care, and thus I put the "" ... but as you said, `planner` and `slicer` simply produce different outputs so one can't just always interchange them.
What *should* work is using a nested target, where the nested one includes p2 and uses planer mode, while the main target uses slicer mode.

**Comment by merks** [comment] 2022-05-18 11:48
It's in the platform's repo.

https://download.eclipse.org/oomph/archive/reports/download.eclipse.org/eclipse/updates/4.24-I-builds/index.html

In general this is helpful for finding repositories:

https://wiki.eclipse.org/Eclipse_Oomph_Authoring#How_to_find_a_P2_repository_at_Eclipse_using_the_Repository_Explorer

**Comment by laeubi** [comment] 2022-05-18 11:51
> It's in the platform's repo.

I think the problem is that there is no feature and you can not select a single bundle in the UI (or has this changed?) so its rather inconvenient to do so.

**Comment by laeubi** [comment] 2022-05-18 12:00
By the way hopefully after the next release of P2 there will be smarter ways to handle this with the fix for https://github.com/eclipse/tycho/issues/898.

**Comment by merks** [comment] 2022-05-18 12:04
@laeubi How will changes in Tycho help in the IDE?  Note that you can include individual bundles in the *.target file.

**Comment by Phillipus** [comment] 2022-05-18 12:35
> What should work is using a nested target, where the nested one includes p2 and uses planer mode, while the main target uses slicer mode.

Tried that. I effectively got the slicer target (so no sat4j)

```
<target name="Nested">
<locations>
    <location includeAllPlatforms="true" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
        <repository location="https://download.eclipse.org/eclipse/updates/4.24-I-builds/"/>
        <unit id="org.eclipse.ecf.filetransfer.httpclient5.feature.feature.group" version="0.0.0"/>
        <unit id="org.eclipse.ecf.core.feature.feature.group" version="0.0.0"/>
        <unit id="org.eclipse.ecf.core.ssl.feature.feature.group" version="0.0.0"/>
        <unit id="org.eclipse.ecf.filetransfer.feature.feature.group" version="0.0.0"/>
        <unit id="org.eclipse.ecf.filetransfer.ssl.feature.feature.group" version="0.0.0"/>
        <unit id="org.eclipse.emf.common.feature.group" version="0.0.0"/>
        <unit id="org.eclipse.emf.ecore.feature.group" version="0.0.0"/>
        <unit id="org.eclipse.equinox.core.feature.feature.group" version="0.0.0"/>
        <unit id="org.eclipse.equinox.p2.core.feature.feature.group" version="0.0.0"/>
        <unit id="org.eclipse.equinox.p2.extras.feature.feature.group" version="0.0.0"/>
        <unit id="org.eclipse.equinox.sdk.feature.group" version="0.0.0"/>
        <unit id="org.eclipse.sdk.ide" version="0.0.0"/>
    </location>
</locations>
</target>
```

And:

```
<target name="Main">
    <locations>
        <location type="Target" uri="file:${project_loc:/com.archimatetool.build}/archi-dev.target" includeAllPlatforms="true" includeConfigurePhase="true" includeMode="slicer" includeSource="true" />
    </locations>
</target>
```

**Comment by Phillipus** [comment] 2022-05-18 12:44
My aim is not really about the Tycho build, but to make all the platform plug-ins and fragments available in the IDE so I (a) don't get the warnings about the missing plug-ins/fragments and (b) so I can add them to a feature project in the first place.

**Comment by Phillipus** [comment] 2022-05-18 14:23
> > It's in the platform's repo.
> 
> I think the problem is that there is no feature and you can not select a single bundle in the UI (or has this changed?) so its rather inconvenient to do so.

Indeed. The Target editor only allows to add features.

**Comment by Phillipus** [comment] 2022-05-18 14:38
> For the target-editor this could be, but if you switch into the source-Tab you can add any IU (Features and Plugins). You even get a basic Content-Assist there when you have at least inserted a opening angular bracket ("<").

Thanks for that!

I added the following to my target file and set it to "slicer" mode:

```xml
<unit id="org.sat4j.core" version="0.0.0"/>
<unit id="org.sat4j.pb" version="0.0.0"/>
```

Now I can launch the product in the IDE and work with the multi-platform bundles.

My concern is that  going forward I have to manually manage dependencies for the target, but I guess there's no real answer.

Is there a reason that the target has to be slicer or planner? Can't there be a best of both worlds?

**Comment by Phillipus** [comment] 2022-05-19 08:37
Thanks for all the help, I appreciate it.

One last question - is there a limitation in the way targets are resolved so that you can't get the best of both worlds - "slicer", for the multi-platform bundles, _and_ "planner", to resolve dependencies?

**Comment by laeubi** [comment] 2022-05-19 08:44
No you can just split this as I said with nested targets, so you add the feature you want to be *planned* to one target and the others as regular items with `slicer`. so the *mode* is global for *one* target file.

**Comment by Phillipus** [comment] 2022-05-19 08:47
> No you can just split this as I said with nested targets, so you add the feature you want to be planned to one target and the others as regular items with slicer. so the mode is global for one target file.

I tried variations of that, but it ended up either being all planner or all slicer but not a combination of both.

**Comment by laeubi** [comment] 2022-05-19 09:06
No problem, good to hear you found a solution.
